version: '3.4'

services:
  api:
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5005:5005
    command: npm run start:dev
